on: workflow_dispatch
name: Build
jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Checkout code
      uses: actions/checkout@v2
#     - name: Unit Tests
#       run: go test -v ./stmt
    - name: Build with "most"
      run: bash build-release.sh -v
    - name: Print dir
      run: ls -l build/windows/0.0.0-dev/ 
    - name: Upload artfact
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: build/windows/0.0.0-dev/usql-0.0.0-dev-windows-amd64.tar.bz2
      
