on: workflow_dispatch
name: Build
jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - name: Checkout code
      uses: actions/checkout@v2
#     - name: Unit Tests
#       run: go test -v ./stmt
    - name: Build with "most"
      run: bash build-release.sh -r
    - name: Print dir
      run: ls -l build/windows/*-dev/ 
    - name: Upload artfact
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: build/windows/*-dev/usql-*-dev-windows-amd64.tar.bz2
      
