on: workflow_dispatch
name: Build
jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: action-zip
      # You may pin to the exact commit or the version.
      # uses: montudor/action-zip@0852c26906e00f8a315c704958823928d8018b28
      uses: montudor/action-zip@v1.0.0
      with:
        # See montudor/action-zip README.md for more info
        args: # optional
    - name: UPX Action
      # You may pin to the exact commit or the version.
      # uses: gacts/upx@65347bae841189e25abe0df3941ce61be5e8bf9c
      uses: gacts/upx@v1.0.1
      with:
        # Input file
        file: # optional
        # Input directory
        dir: # optional
        # Arguments to pass to UPX
        upx_args: 
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Unit Tests
      run: go test -v ./stmt
    - name: Build with "most"
      run: bash build-release.sh -v
